data <- read.table("household_power_consumption.txt",sep =";", header = TRUE, stringsAsFactors = F )
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
newdata <- subset(data, Date >="2007-02-01" & Date <= "2007-02-02")
require("lubridate")
newdata$DtTime <- ymd_hms(paste(newdata$Date, newdata$Time, sep = "_"))
plot(newdata$DtTime, newdata$Global_active_power,  ylab = "Global Active Power (killowatts)", xlab = "", type="n")
lines(newdata$DtTime, newdata$Global_active_power)
dev.copy(png, file = "plot2.png") 
dev.off()
