data <- read.table("household_power_consumption.txt",sep =";", header = TRUE, stringsAsFactors = F )
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
newdata <- subset(data, Date >="2007-02-01" & Date <= "2007-02-02")
require("lubridate")
newdata$DtTime <- ymd_hms(paste(newdata$Date, newdata$Time, sep = "_"))
par(mfrow = c(2, 2),mar = c(4, 4, 4, 2), oma = c(1, 1, 0, 0))
with(newdata, {
        plot(newdata$DtTime, newdata$Global_active_power,  ylab = "Global Active Power (killowatts)", xlab = "", type="n")
        lines(newdata$DtTime, newdata$Global_active_power)
        plot(DtTime, Voltage, ylab = "Voltage", xlab = "datetime", type="n")
        lines(DtTime, Voltage)
        plot(newdata$DtTime, newdata$Sub_metering_1, type="n", ylab= "Energy sub metering", xlab="")
        lines(newdata$DtTime, newdata$Sub_metering_1)
        lines(newdata$DtTime, newdata$Sub_metering_2, col="red")
        lines(newdata$DtTime, newdata$Sub_metering_3, col="blue")
        legend("topright", lwd=1, col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
        plot(DtTime, Global_reactive_power,  ylab = "Global_reactive_power", xlab = "datetime", type="n")
        lines(DtTime, Global_reactive_power)
})

dev.copy(png, file = "plot4.png") 
dev.off()
