data <- read.table("household_power_consumption.txt",sep =";", header = TRUE, stringsAsFactors = F )
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
newdata <- subset(data, Date >="2007-02-01" & Date <= "2007-02-02")
require("lubridate")
newdata$DtTime <- ymd_hms(paste(newdata$Date, newdata$Time, sep = "_"))
plot(newdata$DtTime, newdata$Sub_metering_1, type="n", ylab= "Energy sub metering", xlab="")
lines(newdata$DtTime, newdata$Sub_metering_1)
lines(newdata$DtTime, newdata$Sub_metering_2, col="red")
lines(newdata$DtTime, newdata$Sub_metering_3, col="blue")
legend("topright", lwd=1, col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
png(filename = "plot3.png", width = 480, height = 480)
